// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxjiouxgpycrildioigv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4amlvdXhncHljcmlsZGlvaWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDg1NDEsImV4cCI6MjA2NTIyNDU0MX0.sL3C0PuRmfc4SpdJF6LKDnreJVHG24xNImUJNx00WdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);